version: '2'
services:
  factorio:
    build: .
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - /opt/factorio:/factorio
#    environment:
#      - PUID=1000
#      - PGID=1000
